### ISSUE TITLE
Run supavisor on already hosted postgresql server

### ISSUE THREAD

**Issue by jahnavisana2812** [supabase/supavisor#246]
# Improve documentation

## Describe the problem

There is no proper documentation on how to host the supavisor on the self hosted postgres servers without using the supabase postgres14.If that's possible

## Describe the improvement

Please provide any essential documentation for the above

## Additional context

I was trying to run the docker-compose file with our self hosted url but that seems to be throwing some error 

```
`version: '3'

services:
  supavisor:
    image: supabase/supavisor:1.1.2
    container_name: supavisor
    ports:
      - 4000:4000
      - 5452:5452
      - 6543:6543
    environment:
      PORT: 4000
      PROXY_PORT_SESSION: 5452
      PROXY_PORT_TRANSACTION: 6543
      DATABASE_URL: "postgres://supavisor:XXX@db-cluster:5432/postgres"
      CLUSTER_POSTGRES: "true"
      SECRET_KEY_BASE: "dev"
      VAULT_ENC_KEY: "12345678901234567890123456789032"
      API_JWT_SECRET: "dev"
      METRICS_JWT_SECRET: "dev"
      REGION: "local"
      ERL_AFLAGS: -proto_dist inet_tcp
    command:  sh -c "/app/bin/migrate && /app/bin/server"`
```
Error  shown:
```
`✔ Container supavisor  Created                                                                                                                          0.0s 
Attaching to supavisor
supavisor  | Setting RLIMIT_NOFILE to 100000
supavisor  | 11:06:33.765 [error] Could not create schema migrations table. This error usually happens due to the following:
supavisor  | 
supavisor  |   * The database does not exist
supavisor  |   * The "schema_migrations" table, which Ecto uses for managing
supavisor  |     migrations, was defined by another library
supavisor  |   * There is a deadlock while migrating (such as using concurrent
supavisor  |     indexes with a migration_lock)
supavisor  | 
supavisor  | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
supavisor  | 
supavisor  | To address the second, you can run "mix ecto.drop" followed by
supavisor  | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
supavisor  | configure Ecto to use another table and/or repository for managing
supavisor  | migrations:
supavisor  | 
supavisor  |     config :supavisor, Supavisor.Repo,
supavisor  |       migration_source: "some_other_table_for_schema_migrations",
supavisor  |       migration_repo: AnotherRepoForSchemaMigrations
supavisor  | 
supavisor  | The full error report is shown below.
supavisor  | 
supavisor  | ** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "_supavisor" does not exist
supavisor  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
supavisor  |     (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
supavisor  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
supavisor  |     (ecto_sql 3.10.2) lib/ecto/migrator.ex:756: Ecto.Migrator.verbose_schema_migration/3
supavisor  |     (ecto_sql 3.10.2) lib/ecto/migrator.ex:564: Ecto.Migrator.lock_for_migrations/4
supavisor  |     (ecto_sql 3.10.2) lib/ecto/migrator.ex:433: Ecto.Migrator.run/4
supavisor  |     (ecto_sql 3.10.2) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
supavisor  |     nofile:1: (file)
supavisor exited with code 1`
```
