### ISSUE TITLE
Supavisor fails to query Postgres version 13.10 or earlier

### ISSUE THREAD

**Issue by RTLS** [supabase/supavisor#86]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

For Postgres version 13.10 or earlier, Supavisor is able to connect but unable to complete a query.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone and install Supavisor per the [docs](https://github.com/supabase/supavisor/wiki/Installation-and-Usage)
2. Attempt to connect to Postgres version 13.10 or earlier through Supavisor.
3. Run `select 1;` or a similar query.
4. See error: `[error] Connection closed when state was idle`

## Expected behavior

Supavisor is able to query supported Postgres versions `11.19` and up.

## Screenshots

n/a

## System information

- OS: macOS Ventura 13.2.1
- Postggres 11.19, 12.14, or 13.10
- Version of supabase/supavisor: latest main (5d16420549bde4fa479938cbb40795f8f2b58ebe)

## Additional context

The full error output is:
```
10:55:37.184 [error] Connection closed when state was idle file=lib/supavisor/db_handler.ex line=199 pid=<0.896.0> project=dev_tenant user=postgres
```

The dockerfile for the target Postgres instance is:
```
version: "3"

services:
  postgres:
    image: "postgres:13.10"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200 -c pg_stat_statements.max=10000 -c track_activity_query_size=2048
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

```
